name: E2E Tests

on:
  schedule:
    # 毎日0時(UTC)に実行
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]
    paths:
      - 'client-admin/**/*.ts'
      - 'client-admin/**/*.tsx'
      - 'client-admin/**/*.js'
      - 'client-admin/**/*.jsx'
      - 'client-admin/package.json'
      - 'test/e2e/**/*'
    types: [opened, synchronize, reopened, labeled]

jobs:
  e2e-tests:
    # スケジュールまたはPRの場合に実行（テスト用に一時的にラベル条件を削除）
    if: github.event_name == 'schedule' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./test/e2e/package.json

    - name: Install dependencies
      working-directory: ./test/e2e
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ./test/e2e
      run: npx playwright install --with-deps chromium

    - name: Set up client-admin
      working-directory: ./client-admin
      run: npm ci

    - name: Run Playwright tests
      working-directory: ./test/e2e
      run: npx playwright test
      env:
        BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        NEXT_PUBLIC_API_BASEPATH: 'http://localhost:8000'
        NEXT_PUBLIC_ADMIN_API_KEY: 'test-api-key'

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ./test/e2e/playwright-report/
        retention-days: 30
